### ISSUE TITLE
Debuggable APK doesn't work, showing the Example Domain page

### ISSUE THREAD

**Issue by kyoshino** [mozilla/apk-factory-service#83]
I'd like to debug my app for kyoshino/bzdeck#194. The APK file was generated with [`mozilla-apk-cli`](https://github.com/mozilla/apk-cli) and installed successfully, but when I launch the app on Android, it shows the Example Domain page. I have tried both hosted and packaged app but no luck. Maybe the app origin is not set, loading http://example.com/ instead?

**Comment by mykmelez** [comment]
Hmm, no, I don't know why this is happening. It could be a problem with the CLI, but it could also be an issue with the APK Factory instance that the CLI is using to generate these APKs. If you use the *--endpoint* flag to make the CLI use the production APK factory server, then you could compare the two APKs to see if there are differences between the files.

cc: @wfwalker so he's aware of this issue.

**Comment by kyoshino** [comment]
Any chance to see the issue solved? I had to disable BzDeck's Android compatibility on the [Firefox Marketplace](https://marketplace.firefox.com/app/bzdeck/). :tired_face:

**Comment by kyoshino** [comment]
A traditional `window.alert` debugging have found that it's an issue in my [Web Activities](https://hacks.mozilla.org/2013/01/introducing-web-activities/) code, so I have just disabled the feature in my app. It's difficult to solve the issue without a debuggable APK.

**Comment by kyoshino** [comment]
Another Android WebAppRT issue found on my app: https://github.com/bzdeck/bzdeck/issues/293

**Comment by kumar303** [comment]
I'll ping some folks about who could maybe look at this. The original author is no longer at Mozilla so I'm not sure who's maintaining it.

**Comment by ozten** [comment]
I'm happy to take a look at this in the next couple of days.

**Comment by ozten** [comment]
Can you try 

    mozilla-apk-cli --overrideManifest https://www.bzdeck.com/manifest.webapp https://www.bzdeck.com/manifest.webapp bzdeck_test.apk


`example.com` is provided by the cli app, but should be overwritten server side. This isn't happening, I've not identified why yet. By specifying an explicit `overrideManifest` we won't end up with `example.com`.

I looked in the `classes.dex` file and am seeing `com.bzdeck.www` in the package names, so hopefully this will work.

**Comment by ozten** [comment]
mozilla-apk-cli version 0.0.10 is now published. It automatically sets `overrideManifest` for building hosted apps.
